### ISSUE TITLE
Sliding window pipeline

### ISSUE THREAD

**Issue by michaelmunje** [mars-vision/marsvision#10]
This class will take in an image as input of dynamic image dimensions and will run a sliding window algorithm to classify each window.

We will want a configuration file for this class, which will specify things such as a trained model type and location which we can load.

**Comment by dpalencia** [comment]
Pushed a notebook demonstrating this, though it still needs to handle the edges of the images and stride. We can adapt this code to a module

https://github.com/mars-vision/marsvision/blob/issue/10-sliding-window-pipeline/Prototyping/Notebooks/Sliding-Window.ipynb

**Comment by dpalencia** [comment]
Updated the code to handle image edges, and to use different strides as parameters. Should be ready to implement into a class in our package.

**Comment by michaelmunje** [comment]
I believe if you do something like `git commit -m "Handle image edges and parameter for stride, Issue: #10"`, then it should automatically link the commits to this issue, I recommend doing that in the future so we can easily see the changes.
