### ISSUE TITLE
Sliding Window Pipeline

### ISSUE THREAD

**Issue by michaelmunje** [mars-vision/marsvision#16]
Add SlidingWindowPipeline, which will run the sliding window algorithm on a set of images, run inference for each subimage, and save the results to a database.

**Comment by dpalencia** [comment]
Confirmed that the sliding window pipeline works with the model class in CNN mode using our newly trained model.

Also played around with annotating parent images using these inferences--useful for seeing how the model is doing on "live" data at a glance.

https://github.com/mars-vision/marsvision/blob/dev/Prototyping/Notebooks/Sliding%20Window%20DB.ipynb
