### ISSUE TITLE
Save results to database

### ISSUE THREAD

**Issue by michaelmunje** [mars-vision/marsvision#7]
(Only work on this after we finish: https://github.com/dpalencia/marsvision/issues/10)

We will need to add the ability to save the data from inference (running the pipeline on HiRISE images). 

We can use: https://docs.python.org/3/library/sqlite3.html

Also, we need to decide the specific data that will be saved. For now, we will omit metadata available via NASA APIs.

**Comment by dpalencia** [comment]
### Proposed database tables

1. Windows. Attributes:
- ID (references corresponding entry in global table)
- x and y coordinate
- latitude
- longitude
- predicted class

2. Global (parent image). Attributes:
- Window size
- stride length
- image metadata

**Comment by dpalencia** [comment]
Re: the latest push, 

The sliding window class can now write data to a database with two tables as specified above--one table for predictions and window information, and one for global information shared by the corresponding windows.

To do:
Need to fix some mypy type errors, write tests, correct CI errors we're getting, and handle creation of a new database file when one does not exist.
